[project]
name = "vfx-prodtracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.3.0",
    "sphinx>=8.2.3",
    "sphinxcontrib-napoleon>=0.7",
]

[tool.uv.workspace]
members = ["tracktor_server"]

