[project]
name = "tracktor-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.3.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
